services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: deep_arch
      POSTGRES_PASSWORD: deep_arch
      POSTGRES_DB: deep_arch
    volumes:
      - ./scripts_db_init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - deep_arch_pg:/var/lib/postgresql/data

volumes:
  deep_arch_pg:
